import django
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import *


urlpatterns = [
    path('', start, name='start'),
    path('word_1kk/<int:period>', word_1kk, name='word_1kk'),
    path('word_vkk/<int:period>', word_vkk, name='word_vkk'),
    path('login/', login_user, name='login'),
    path('show_periods/', show_periods, name='show_periods'),
    path('new_period/', new_period, name='new_period'),
    path('edit_period/<int:id>', edit_period, name='edit_period'),
    path('delete_period/<int:id>', delete_period, name='delete_period'),
    path('find_results/<int:period>_<str:type>', find_results, name='find_results'),
    path('change_pass/<int:id>', change_password, name='change_password'),
    path('change_pass_delegate/<int:id>', change_password_delegate, name='change_password_delegate'),
    path('main/', exp_card, name='main'),
    path('add_target/', add_target, name='add_target'),
    path('all_expcard/<int:period>_<str:type_mo>_<str:type_emp>', all_expcards, name='all_expcards'),
    path('filter_expcards/<int:period>_<str:type_mo>_<str:type_emp>', filter_expcards, name='filter_expcards'),
    path('filter_specs/<int:period>', filter_specs, name='filter_specs'),
    path('find_list_cards_spec/', find_list_cards_spec, name='find_list_cards_spec'),
    path('statistics_spec/', statistics_spec, name='statistics_spec'),
    path('choose_spec_stats/<int:period>', choose_spec_stats, name='choose_spec_stats'),
    path('statistics_cert/', statistics_cert, name='statistics_cert'),
    path('choose_certs_crits/', choose_certs_crits, name='choose_certs_crits'),
    path('choose_cert_stats/<int:period>', choose_cert_stats, name='choose_cert_stats'),
    path('main_stat_cert/<int:period>', main_stat_cert, name='main_stat_cert'),
    path('main_stat_spec/<int:period>', main_stat_spec, name='main_stat_spec'),
    path('targets_criteria/<int:specid>_<int:certid>', targets_criteria, name='targets_criteria'),
    path('targets_operator/<int:certid>', targets_operator, name='targets_operator'),
    path('new_crit_operator/<int:certid>', new_crit_operator, name='new_crit_operator'),
    path('change_targets_criteria/', change_targets_criteria, name='change_targets_criteria'),
    path('filter_delegates/<str:per>', filter_delegates, name='filter_delegates'),
    path('filter_atts/<int:period>', filter_atts, name='filter_atts'),
    path('all_criterias/<int:period>', all_criterias, name='all_criterias'),
    path('find_criterias/', find_criterias, name='find_criterias'),
    path('choose_expcards/', choose_expcards, name='choose_expcards'),
    path('all_results/<str:typ>_<int:period>_<int:page>', all_results, name='all_results'),
    path('choose_results/', choose_results, name='choose_results'),
    path('spec_results/<int:id>', spec_results, name='spec_results'),
    path('summary_results/<str:fio>_<int:period>_<int:mo>_<int:pos>', summary_results, name='summary_results'),
    path('cert_results/<int:id>', cert_results, name='cert_results'),
    path('cert_results_from_expcard/<int:id>', cert_results_from_expcard, name='cert_results_from_expcard'),
    path('cert_results_from_targets/<int:id>', cert_results_from_targets, name='cert_results_from_targets'),
    path('cards_spec/', list_cards_spec, name='cards_spec'),
    path('list_cards_spec_mo/', list_cards_spec_mo, name='list_cards_spec_mo'),
    path('list_targets_deleg/', list_targets_deleg, name='list_targets_deleg'),
    path('delete_spec_card/<int:id>', delete_spec_card, name='delete_spec_card'),
    path('delete_target_deleg/<int:id>', delete_target_deleg, name='delete_target_deleg'),
    path('profile/', user_profile, name='profile'),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='registration/password_reset.html'
         ),
         name='password_reset'),
    path('accounts/password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='registration/password_reset_donee.html'
         ),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
            template_name='registration/password_reset_conf.html'
         ),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
            template_name='registration/password_reset_complet.html'
         ),
         name='password_reset_complete'),
    path('register/', registr, name='registration'),
    path('sum/', SumTab, name='sumtab'),
    path('update_all/', update_all, name='update_all'),
    path('import/', import_excel, name='import_excel'),
    path('add_cert/<int:period>', add_cert, name='add_cert'),
    path('delete_cert/<int:id>', delete_cert, name='delete_cert'),
    path('delete_target/<int:id>', delete_target, name='delete_target'),
    path('add_spec/<int:period>', add_spec, name='add_spec'),
    path('add_delegate/<int:period>', add_delegate, name='add_delegate'),
    path('delete_spec/<int:id>', delete_spec, name='delete_spec'),
    path('delete_delegate/<int:id>', delete_delegate, name='delete_delegate'),
    path('check_list/', check_list, name='check_list'),
    path('choose_criterias/', choose_criterias, name='choose_criterias'),
    path('delete_cert_list/<int:period>', delete_cert_list, name='delete_cert_list'),
    path('spec_post_list/<int:period>', spec_post_list, name='spec_post_list'),
    path('delegate_post_list/<int:period>', delegate_post_list, name='delegate_post_list'),
    path('cert_post_list/<int:period>', cert_post_list, name='spec_post_list'),
    path('find_spec/<int:period>', find_spec, name='find_spec'),
    path('find_delegate/<int:period>', find_delegate, name='find_delegate'),
    path('find_cert/<int:period>', find_cert, name='find_cert'),
    path('delete_spec_list/<int:period>', delete_spec_list, name='delete_spec_list'),
    path('delete_delegate_list/<int:period>', delete_delegate_list, name='delete_delegate_list'),
    path('delete_all/', delete_all, name='delete_all'),
    path('edit_cert/<int:id>', edit_cert, name='edit_cert'),
    path('edit_spec/<int:id>', edit_spec, name='edit_spec'),
    path('edit_delegate/<int:id>', edit_delegate, name='edit_delegate'),
    path('target_mo/<int:id>', target_mo, name='target_mo'),
    path('target_spec/<int:id>', target_spec, name='target_spec'),
    path('change_target_mo/<int:id>', change_target_mo, name='change_target_mo'),
    path('new_criteria/<int:id>', new_criteria, name='new_criteria'),
    path('show_crit_recs/<int:id_cert>', show_crit_recs, name='show_crit_recs'),
    path('show_crit_cards/<int:id_inter>', show_crit_cards, name='show_crit_cards'),
    path('delete_crit_rec/<int:id>', delete_crit_rec, name='delete_crit_rec'),
    path('delete_crit_target/<int:id>', delete_crit_target, name='delete_crit_target'),
]
