# Generated by Django 3.2.7 on 2021-11-15 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cat', models.CharField(max_length=250, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='AttPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pos', models.CharField(max_length=250, verbose_name='Название должности аттестуемого')),
            ],
            options={
                'verbose_name': 'Должность аттестуемого',
                'verbose_name_plural': 'Должности аттестуемых',
            },
        ),
        migrations.CreateModel(
            name='certified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att_code', models.CharField(max_length=25, unique=True, verbose_name='Код аттестуемого')),
                ('year', models.IntegerField(verbose_name='Год аттестации')),
                ('month', models.CharField(max_length=10, verbose_name='Месяц аттестации')),
                ('FIO', models.CharField(max_length=100, verbose_name='ФИО')),
                ('Organization', models.CharField(max_length=300, verbose_name='Образовательная организация')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.attcategories', verbose_name='Заявленная категория')),
            ],
            options={
                'verbose_name': 'Аттестуемый',
                'verbose_name_plural': 'Аттестуемые',
            },
        ),
        migrations.CreateModel(
            name='ExpLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_level', models.CharField(max_length=250, verbose_name='Уровень эксперта')),
            ],
            options={
                'verbose_name': 'Уровень эксперта',
                'verbose_name_plural': 'Уровни экспертов',
            },
        ),
        migrations.CreateModel(
            name='ExpPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pos', models.CharField(max_length=250, verbose_name='Название должности эксперта')),
            ],
            options={
                'verbose_name': 'Должность эксперта',
                'verbose_name_plural': 'Должности экспертов',
            },
        ),
        migrations.CreateModel(
            name='MunObr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_MO', models.CharField(max_length=250, verbose_name='Наименование МО')),
            ],
            options={
                'verbose_name': 'МО',
                'verbose_name_plural': 'МО',
            },
        ),
        migrations.CreateModel(
            name='Summary_table_gos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO_expert', models.CharField(max_length=250, verbose_name='ФИО эксперта')),
                ('count', models.IntegerField(default=0, verbose_name='Количество экспертиз')),
                ('coincidence_common', models.IntegerField(null=True, verbose_name='Совпадения на первом этапе')),
                ('coincidence_general', models.IntegerField(null=True, verbose_name='Совпадения на втором этапе')),
                ('coincidence_operator', models.IntegerField(null=True, verbose_name='Совпадения с оператором')),
                ('Percent', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='%')),
                ('Level_expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.explevel', verbose_name='Уровень эксперта')),
                ('MO_expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.munobr', verbose_name='МО эксперта')),
                ('Position_expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.expposition', verbose_name='Должность эксперта')),
            ],
            options={
                'verbose_name': 'Результат по эксперту подведы',
                'verbose_name_plural': 'Результаты по экспертам подведы',
            },
        ),
        migrations.CreateModel(
            name='Summary_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO_expert', models.CharField(max_length=250, verbose_name='ФИО эксперта')),
                ('count', models.IntegerField(default=0, verbose_name='Количество экспертиз')),
                ('coincidence_common', models.IntegerField(null=True, verbose_name='Совпадения на первом этапе')),
                ('coincidence_general', models.IntegerField(null=True, verbose_name='Совпадения на втором этапе')),
                ('coincidence_operator', models.IntegerField(null=True, verbose_name='Совпадения с оператором')),
                ('Percent', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='%')),
                ('Level_expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.explevel', verbose_name='Уровень эксперта')),
                ('MO_expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.munobr', verbose_name='МО эксперта')),
                ('Position_expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.expposition', verbose_name='Должность эксперта')),
            ],
            options={
                'verbose_name': 'Результат по эксперту',
                'verbose_name_plural': 'Результаты по экспертам',
            },
        ),
        migrations.CreateModel(
            name='intermediate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания карты')),
                ('result', models.CharField(max_length=30, verbose_name='Результат')),
                ('cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.certified', verbose_name='Аттестуемый')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.explevel', verbose_name='Этап анализа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись о карте',
                'verbose_name_plural': 'Записи о картах',
            },
        ),
        migrations.CreateModel(
            name='ExpCardsGos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания карты')),
                ('FIO_expert', models.CharField(max_length=250, verbose_name='ФИО эксперта')),
                ('Name_Org_expert', models.CharField(max_length=300, verbose_name='ОО эксперта')),
                ('FIO_att', models.CharField(max_length=250, verbose_name='ФИО аттестуемого')),
                ('Name_Org_att', models.CharField(max_length=300, verbose_name='ОО аттестуемого')),
                ('Result', models.CharField(max_length=30, verbose_name='Результат')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.attcategories', verbose_name='Заявленная категория')),
                ('Level_expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.explevel', verbose_name='Уровень эксперта')),
                ('MO_att', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attMOgos', to='expcard.munobr', verbose_name='МО аттестуемого')),
                ('MO_expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expMOgos', to='expcard.munobr', verbose_name='МО эксперта')),
                ('Position_att', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.attposition', verbose_name='Должность аттестуемого')),
                ('Position_expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.expposition', verbose_name='Должность эксперта')),
            ],
            options={
                'verbose_name': 'Экспертная карта подведы',
                'verbose_name_plural': 'Экспертные карты подведы',
            },
        ),
        migrations.CreateModel(
            name='ExpCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания карты')),
                ('FIO_expert', models.CharField(max_length=250, verbose_name='ФИО эксперта')),
                ('Name_Org_expert', models.CharField(max_length=300, verbose_name='ОО эксперта')),
                ('FIO_att', models.CharField(max_length=250, verbose_name='ФИО аттестуемого')),
                ('Name_Org_att', models.CharField(max_length=300, verbose_name='ОО аттестуемого')),
                ('Result', models.CharField(max_length=30, verbose_name='Результат')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.attcategories', verbose_name='Заявленная категория')),
                ('Level_expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.explevel', verbose_name='Уровень эксперта')),
                ('MO_att', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attMO', to='expcard.munobr', verbose_name='МО аттестуемого')),
                ('MO_expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expMO', to='expcard.munobr', verbose_name='МО эксперта')),
                ('Position_att', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.attposition', verbose_name='Должность аттестуемого')),
                ('Position_expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.expposition', verbose_name='Должность эксперта')),
            ],
            options={
                'verbose_name': 'Экспертная карта',
                'verbose_name_plural': 'Экспертные карты',
            },
        ),
        migrations.CreateModel(
            name='CokoGosExpCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания карты')),
                ('FIO_expert', models.CharField(max_length=250, verbose_name='ФИО эксперта')),
                ('Name_Org_expert', models.CharField(max_length=300, verbose_name='ОО эксперта')),
                ('FIO_att', models.CharField(max_length=250, verbose_name='ФИО аттестуемого')),
                ('Name_Org_att', models.CharField(max_length=300, verbose_name='ОО аттестуемого')),
                ('Result', models.CharField(max_length=30, verbose_name='Результат')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.attcategories', verbose_name='Заявленная категория')),
                ('Level_expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.explevel', verbose_name='Уровень эксперта')),
                ('MO_att', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cokogosattMO', to='expcard.munobr', verbose_name='МО аттестуемого')),
                ('MO_expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cokogosexpMO', to='expcard.munobr', verbose_name='МО эксперта')),
                ('Position_att', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.attposition', verbose_name='Должность аттестуемого')),
                ('Position_expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.expposition', verbose_name='Должность эксперта')),
            ],
            options={
                'verbose_name': 'Экспертная карта оператора гос',
                'verbose_name_plural': 'Экспертные карты оператора гос',
            },
        ),
        migrations.CreateModel(
            name='CokoExpCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания карты')),
                ('FIO_expert', models.CharField(max_length=250, verbose_name='ФИО эксперта')),
                ('Name_Org_expert', models.CharField(max_length=300, verbose_name='ОО эксперта')),
                ('FIO_att', models.CharField(max_length=250, verbose_name='ФИО аттестуемого')),
                ('Name_Org_att', models.CharField(max_length=300, verbose_name='ОО аттестуемого')),
                ('Result', models.CharField(max_length=30, verbose_name='Результат')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.attcategories', verbose_name='Заявленная категория')),
                ('Level_expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.explevel', verbose_name='Уровень эксперта')),
                ('MO_att', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cokoattMO', to='expcard.munobr', verbose_name='МО аттестуемого')),
                ('MO_expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cokoexpMO', to='expcard.munobr', verbose_name='МО эксперта')),
                ('Position_att', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.attposition', verbose_name='Должность аттестуемого')),
                ('Position_expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.expposition', verbose_name='Должность эксперта')),
            ],
            options={
                'verbose_name': 'Экспертная карта оператора',
                'verbose_name_plural': 'Экспертные карты оператора',
            },
        ),
        migrations.AddField(
            model_name='certified',
            name='MO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attMOcert', to='expcard.munobr', verbose_name='Муниципальное образование'),
        ),
        migrations.AddField(
            model_name='certified',
            name='Position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.attposition', verbose_name='Должность'),
        ),
    ]
