# Generated by Django 3.2.7 on 2021-12-15 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expcard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cards_criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(max_length=1000, verbose_name='Замечание специалиста')),
            ],
            options={
                'verbose_name': 'Запись о замечании специалиста',
                'verbose_name_plural': 'Записи о замечаниях специалистов',
            },
        ),
        migrations.CreateModel(
            name='criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_criteria', models.CharField(max_length=50, verbose_name='Критерий')),
            ],
            options={
                'verbose_name': 'Критерий',
                'verbose_name_plural': 'Критерии',
            },
        ),
        migrations.CreateModel(
            name='criteria_export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO_spec', models.CharField(max_length=250, verbose_name='ФИО специалиста')),
                ('FIO_att', models.CharField(max_length=250, verbose_name='ФИО аттестуемого')),
                ('Result', models.CharField(default='Установить', max_length=30, verbose_name='Результат')),
                ('info', models.TextField(max_length=1000, verbose_name='Замечание специалиста')),
                ('Category', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='expcard.attcategories', verbose_name='Аттестационная категория')),
            ],
            options={
                'verbose_name': 'Замечание специалиста',
                'verbose_name_plural': 'Замечания специалистов',
            },
        ),
        migrations.CreateModel(
            name='delegates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=100, verbose_name='Период работы')),
                ('FIO', models.CharField(max_length=100, verbose_name='ФИО')),
                ('Organization', models.CharField(max_length=300, verbose_name='Образовательная организация')),
                ('email', models.CharField(max_length=150, verbose_name='email')),
                ('target', models.CharField(default='Нет', max_length=10, verbose_name='Назначения')),
            ],
            options={
                'verbose_name': 'Уполномоченный',
                'verbose_name_plural': 'Уполномоченные',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pos', models.CharField(max_length=250, verbose_name='Название должности аттестуемого')),
                ('type_pos', models.CharField(default='Специалист', max_length=20, verbose_name='Тип должности')),
            ],
            options={
                'verbose_name': 'Должность аттестуемого',
                'verbose_name_plural': 'Должности аттестуемых',
            },
        ),
        migrations.CreateModel(
            name='specialists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=100, verbose_name='Период работы')),
                ('FIO', models.CharField(max_length=100, verbose_name='ФИО')),
                ('Organization', models.CharField(max_length=300, verbose_name='Образовательная организация')),
                ('email', models.CharField(max_length=150, verbose_name='email')),
                ('target', models.CharField(default='Нет', max_length=10, verbose_name='Назначения')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
            },
        ),
        migrations.CreateModel(
            name='targets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания назначения')),
            ],
            options={
                'verbose_name': 'Назначение',
                'verbose_name_plural': 'Назначения',
            },
        ),
        migrations.CreateModel(
            name='targets_mo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Назначение МО',
                'verbose_name_plural': 'Назначения МО',
            },
        ),
        migrations.RemoveField(
            model_name='cokogosexpcards',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='cokogosexpcards',
            name='Level_expert',
        ),
        migrations.RemoveField(
            model_name='cokogosexpcards',
            name='MO_att',
        ),
        migrations.RemoveField(
            model_name='cokogosexpcards',
            name='MO_expert',
        ),
        migrations.RemoveField(
            model_name='cokogosexpcards',
            name='Position_att',
        ),
        migrations.RemoveField(
            model_name='cokogosexpcards',
            name='Position_expert',
        ),
        migrations.RemoveField(
            model_name='expcardsgos',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='expcardsgos',
            name='Level_expert',
        ),
        migrations.RemoveField(
            model_name='expcardsgos',
            name='MO_att',
        ),
        migrations.RemoveField(
            model_name='expcardsgos',
            name='MO_expert',
        ),
        migrations.RemoveField(
            model_name='expcardsgos',
            name='Position_att',
        ),
        migrations.RemoveField(
            model_name='expcardsgos',
            name='Position_expert',
        ),
        migrations.RemoveField(
            model_name='summary_table_gos',
            name='Level_expert',
        ),
        migrations.RemoveField(
            model_name='summary_table_gos',
            name='MO_expert',
        ),
        migrations.RemoveField(
            model_name='summary_table_gos',
            name='Position_expert',
        ),
        migrations.AlterModelOptions(
            name='explevel',
            options={'verbose_name': 'Этап всестороннего анализа', 'verbose_name_plural': 'Этапы всестороннего анализа'},
        ),
        migrations.RemoveField(
            model_name='intermediate',
            name='user',
        ),
        migrations.AddField(
            model_name='certified',
            name='target',
            field=models.CharField(default='Нет', max_length=10, verbose_name='Назначения'),
        ),
        migrations.AddField(
            model_name='expcards',
            name='inter',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='expcard.intermediate', verbose_name='Должность аттестуемого'),
        ),
        migrations.AddField(
            model_name='expcards',
            name='type_MO',
            field=models.CharField(default='Муниципалитет', max_length=20, verbose_name='Тип МО карты'),
        ),
        migrations.AddField(
            model_name='expcards',
            name='type_emp',
            field=models.CharField(default='Специалист', max_length=20, verbose_name='Тип сотрудника'),
        ),
        migrations.AddField(
            model_name='intermediate',
            name='operator_choice',
            field=models.CharField(default='Специалист', max_length=50, verbose_name='Тип карты оператора'),
        ),
        migrations.AddField(
            model_name='munobr',
            name='type_MO',
            field=models.CharField(default='Муниципалитет', max_length=100, verbose_name='Тип МО'),
        ),
        migrations.AddField(
            model_name='summary_table',
            name='type_MO',
            field=models.CharField(default='Муниципалитет', max_length=20, verbose_name='Тип МО результата'),
        ),
        migrations.AlterField(
            model_name='expcards',
            name='date_add',
            field=models.DateTimeField(verbose_name='Дата создания карты'),
        ),
        migrations.AlterField(
            model_name='explevel',
            name='name_level',
            field=models.CharField(max_length=250, verbose_name='Этап всестороннего анализа'),
        ),
        migrations.DeleteModel(
            name='CokoExpCards',
        ),
        migrations.DeleteModel(
            name='CokoGosExpCards',
        ),
        migrations.DeleteModel(
            name='ExpCardsGos',
        ),
        migrations.DeleteModel(
            name='Summary_table_gos',
        ),
        migrations.AddField(
            model_name='targets_mo',
            name='MO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targetsMO', to='expcard.munobr', verbose_name='Муниципальное образование'),
        ),
        migrations.AddField(
            model_name='targets_mo',
            name='delegate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.delegates', verbose_name='Уполномоченный'),
        ),
        migrations.AddField(
            model_name='targets',
            name='cert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.certified', verbose_name='Аттестуемый'),
        ),
        migrations.AddField(
            model_name='targets',
            name='delegate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.delegates', verbose_name='Уполномоченный'),
        ),
        migrations.AddField(
            model_name='targets',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.specialists', verbose_name='Специалист'),
        ),
        migrations.AddField(
            model_name='specialists',
            name='MO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specMO', to='expcard.munobr', verbose_name='Муниципальное образование'),
        ),
        migrations.AddField(
            model_name='specialists',
            name='Position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.position', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='delegates',
            name='MO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegatesMO', to='expcard.munobr', verbose_name='Муниципальное образование'),
        ),
        migrations.AddField(
            model_name='criteria_export',
            name='MO_att',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='MO_att', to='expcard.munobr', verbose_name='МО аттестуемого'),
        ),
        migrations.AddField(
            model_name='criteria_export',
            name='MO_spec',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='MO_exp', to='expcard.munobr', verbose_name='МО специалиста'),
        ),
        migrations.AddField(
            model_name='criteria_export',
            name='Position_att',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='CritAttPos', to='expcard.position', verbose_name='Должность специалиста'),
        ),
        migrations.AddField(
            model_name='criteria_export',
            name='Position_spec',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='CritExpPos', to='expcard.position', verbose_name='Должность специалиста'),
        ),
        migrations.AddField(
            model_name='criteria_export',
            name='criteria',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='expcard.criteria', verbose_name='Критерий'),
        ),
        migrations.AddField(
            model_name='criteria_export',
            name='id_cards_criteria',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='expcard.cards_criteria', verbose_name='ID записи'),
        ),
        migrations.AddField(
            model_name='cards_criteria',
            name='cert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.certified', verbose_name='Аттестуемый'),
        ),
        migrations.AddField(
            model_name='cards_criteria',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.criteria', verbose_name='Критерий'),
        ),
        migrations.AddField(
            model_name='cards_criteria',
            name='inter',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='expcard.intermediate', verbose_name='Результат'),
        ),
        migrations.AddField(
            model_name='cards_criteria',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.specialists', verbose_name='Специалист'),
        ),
        migrations.AddField(
            model_name='intermediate',
            name='spec',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='expcard.specialists', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='certified',
            name='Position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='expcards',
            name='Position_att',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AttPos', to='expcard.position', verbose_name='Должность аттестуемого'),
        ),
        migrations.AlterField(
            model_name='expcards',
            name='Position_expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ExpPos', to='expcard.position', verbose_name='Должность эксперта'),
        ),
        migrations.AlterField(
            model_name='summary_table',
            name='Position_expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expcard.position', verbose_name='Должность эксперта'),
        ),
        migrations.DeleteModel(
            name='AttPosition',
        ),
        migrations.DeleteModel(
            name='ExpPosition',
        ),
    ]
