# Generated by Django 3.2.7 on 2021-12-16 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expcard', '0002_auto_20211215_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
    ]
