# Generated by Django 3.2.7 on 2021-12-26 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expcard', '0006_auto_20211226_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Форма аттестации')),
            ],
            options={
                'verbose_name': 'Форма аттестации',
                'verbose_name_plural': 'Формы аттестации',
            },
        ),
        migrations.AddField(
            model_name='certified',
            name='att_form',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='expcard.attform', verbose_name='Форма аттестации'),
        ),
    ]
