# Generated by Django 3.2.7 on 2022-01-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expcard', '0007_auto_20211226_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards_criteria',
            name='to_deleg',
            field=models.BooleanField(default=False, verbose_name='Отправлено уполномоченному'),
        ),
    ]
