# Generated by Django 3.2.7 on 2022-01-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expcard', '0008_cards_criteria_to_deleg'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards_criteria',
            name='to_operator',
            field=models.BooleanField(default=False, verbose_name='Отправлено оператору'),
        ),
    ]
