# Generated by Django 3.2.7 on 2022-01-12 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expcard', '0009_cards_criteria_to_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards_criteria',
            name='to_operator',
        ),
    ]
