# Generated by Django 3.2.7 on 2022-01-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expcard', '0010_remove_cards_criteria_to_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards_criteria',
            name='from_operator',
            field=models.BooleanField(default=False, verbose_name='От оператора'),
        ),
    ]
