# Generated by Django 3.2.7 on 2022-02-03 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expcard', '0011_cards_criteria_from_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='kind_oo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Вид ОО')),
            ],
            options={
                'verbose_name': 'Вид ОО',
                'verbose_name_plural': 'Виды ОО',
            },
        ),
        migrations.CreateModel(
            name='type_oo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип ОО')),
            ],
            options={
                'verbose_name': 'Тип ОО',
                'verbose_name_plural': 'Типы ОО',
            },
        ),
        migrations.CreateModel(
            name='oo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, verbose_name='Полное наименование ОО')),
                ('short_name', models.CharField(max_length=100, verbose_name='Краткое наименование ОО')),
                ('address', models.TextField(verbose_name='Адрес ОО')),
                ('phone', models.PositiveIntegerField(blank=True, null=True, verbose_name='Телефон ОО')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта ОО')),
                ('url', models.URLField(max_length=254, verbose_name='Адрес сайта ОО')),
                ('kind', models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='expcard.kind_oo', verbose_name='Вид ОО')),
                ('mo', models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='expcard.munobr', verbose_name='Муниципальное образование ОО')),
            ],
            options={
                'verbose_name': 'Образовательная организация',
                'verbose_name_plural': 'Образовательные организации',
            },
        ),
        migrations.AddField(
            model_name='kind_oo',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expcard.type_oo', verbose_name='Тип'),
        ),
    ]
