# Generated by Django 3.2.7 on 2022-02-08 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expcard', '0012_auto_20220203_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oo',
            name='kind',
        ),
        migrations.AddField(
            model_name='certified',
            name='result',
            field=models.CharField(default='Нет результата', max_length=20, verbose_name='Итоговый результат'),
        ),
        migrations.AddField(
            model_name='oo',
            name='type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='expcard.type_oo', verbose_name='Тип ОО'),
        ),
        migrations.DeleteModel(
            name='kind_oo',
        ),
    ]
