"""
Django settings for attestation project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import ldap
from django_auth_ldap.config import ActiveDirectoryGroupType
from django_auth_ldap.config import LDAPSearch

#Подключение к AD DC для ldap аутентификации
AUTH_LDAP_SERVER_URI = 'ldap://172.16.55.1'
AUTH_LDAP_BIND_DN = "CN=svc-att-exp,OU=Service Users,OU=Users,OU=Core,OU=COKO,DC=coko38,DC=ru"
AUTH_LDAP_BIND_PASSWORD = "Rfv5tgb6!@#"
AUTH_LDAP_USER_SEARCH = LDAPSearch(
            "OU=Users,OU=CMN,OU=COKO,DC=coko38,DC=ru", ldap.SCOPE_SUBTREE, "sAMAccountName=%(user)s"
            )

AUTH_LDAP_USER_ATTR_MAP = {
            "username": "sAMAccountName",
                "first_name": "givenName",
                    "last_name": "sn",
                        "email": "mail",
}
AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
            "OU=Groups,OU=CMN,OU=COKO,DC=coko38,DC=ru", ldap.SCOPE_SUBTREE, "(objectCategory=Group)"
            )
AUTH_LDAP_GROUP_TYPE = ActiveDirectoryGroupType(name_attr="cn")
AUTH_LDAP_USER_FLAGS_BY_GROUP = {
            "is_superuser": "CN=ais_exp,OU=Groups,OU=CMN,OU=COKO,DC=coko38,DC=ru",
            "is_staff": "CN=AG_Regular,OU=Groups,OU=CMN,OU=COKO,DC=coko38,DC=ru"
            }
AUTH_LDAP_FIND_GROUP_PERMS = True
AUTH_LDAP_CACHE_GROUPS = True
AUTH_LDAP_GROUP_CACHE_TIMEOUT = 1  # 1 hour cache

AUTHENTICATION_BACKENDS = [
            'django_auth_ldap.backend.LDAPBackend',
                'django.contrib.auth.backends.ModelBackend',
]

# Подключение к ldap для получения аттрибутов пользователя
AD_SERV = 'srv-ad-1.coko38.ru'
AD_US = #############
AD_PASS = ############
AD_SEARCH = 'ou=Users,ou=CMN,ou=COKO,dc=coko38,dc=ru'

#Сети, для которых разрешено выполнение функций с персоналкой и вход в admin
ALLOWED_NETWORKS=['172.16.54.0/24','172.16.30.0/24']

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
ST_DIR = BASE_DIR.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ow5h8=^jxq6)u7pg1_vew%oqqr^+ovjoumv1)4d8z@9q&w*$=t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'expcard.apps.ExpcardConfig',
    'import_export',
    'pylightxl',
    'openpyxl'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'expcard.middleware.AdminWhitelistMiddleware',
]

ROOT_URLCONF = 'attestation.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'attestation.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': #########,
        'USER': ##########,
        'PASSWORD': #########,
        'HOST': 'srv-dev.coko38.ru',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'connect_timeout': 120,
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Asia/Irkutsk'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(ST_DIR, 'static')

LOGIN_REDIRECT_URL = 'start'
LOGOUT_REDIRECT_URL = 'start'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'noreplay@coko38.ru'
EMAIL_HOST = 'smtp.office365.com'
EMAIL_HOST_USER = ################
EMAIL_HOST_PASSWORD = ##################
EMAIL_PORT = 587


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
